/*
 * dicestrings.inc
 *
 *  Created: 2020-12-08 15:52:24
 *   Author: maste
 */ 


 ;==============================================================================
; Definition of strings
;==============================================================================
	Str_1:		.DB "Welcome!",0,0			
	Hello_str1: .DB "Hello",0
	Dice_start: .DB "Welcome to the dice game",0,0
	Dice_roll:	.DB "Rolling the dice"
	